# Generated by Django 3.2 on 2022-09-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(db_column='IdCountry', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='CountryName', max_length=350)),
            ],
            options={
                'db_table': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(db_column='IdDepartment', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=20)),
            ],
            options={
                'db_table': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Municipalities',
            fields=[
                ('id', models.AutoField(db_column='IdMunicipality', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=150)),
            ],
            options={
                'db_table': 'Municipalities',
            },
        ),
    ]
