# Generated by Django 3.2 on 2022-09-29 21:04

import apps.utils.directory_path
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkInfo',
            fields=[
                ('id', models.AutoField(db_column='IdDepartment', primary_key=True, serialize=False)),
                ('link_name', models.CharField(blank=True, db_column='Name', max_length=150, null=True)),
                ('generated_link', models.CharField(blank=True, db_column='GeneratedLink', max_length=20, null=True)),
                ('comments', models.TextField(blank=True, db_column='Comment', null=True)),
                ('attachment', models.FileField(blank=True, db_column='Attachment', null=True, upload_to=apps.utils.directory_path.file_path)),
            ],
            options={
                'db_table': 'LinkInfo',
            },
        ),
        migrations.CreateModel(
            name='ProcessSteps',
            fields=[
                ('id', models.AutoField(db_column='IdProcessExtra', primary_key=True, serialize=False)),
                ('step_name', models.TextField(db_column='StepName')),
                ('is_done', models.BooleanField(default=False, help_text='Set to true when the user have verified its email address.')),
                ('link_info', models.ForeignKey(db_column='IdLinkInfo', on_delete=django.db.models.deletion.CASCADE, to='administrators.linkinfo')),
            ],
            options={
                'db_table': 'ProcessSteps',
            },
        ),
    ]
